
jobs:
- job: 'Ubuntu_16_04'
  pool: 'NNI CI GPU'

  steps:
  - script: python3 -m pip install twine --user
    displayName: 'Install twine'
  - script: |
      python3 setup.py --version $(version) bdist
    displayName: 'build bdsit'
#  - script: |
#      twine upload --repository testpypi dist/*
#    displayName: 'upload package to testpypi'

  - script: |
      twine upload -u chicm -p Pass@1234pass dist/*
    displayName: 'upload package to testpypi'

